# version: '3'
services:
  mysql:
    image: "mariadb:10.4"
    platform: linux/x86_64
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Ishu2005
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    restart: always
    networks:
      - webnet

  flask:
    build: .
    ports:
      - "5000:5000"
    command: sh -c "sleep 10s ; python run.py"
    depends_on:
      - mysql
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:Ishu2005@mysql:3306/db
    networks:
      - webnet

networks:
  webnet:
    name: webnet
